language: python
sudo: required
dist: xenial

python:
  - "3.6"
  - "3.7"

os:
  - linux

install:
  - pip install pytest
  - pip install -r requirements.txt
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - pytest
